POST http://localhost:3000/api/job
Content-Type: application/json

{
    "job": {
        "callback_url": "http://499fe07c74b2.ngrok.io/job",
        "created_on": "2021-05-17T19:07:32.407Z",
        "id": "zEmtqu2huLBz",
        "media_url": "http://localhost:3000/media/sample-1.mp3",
        "name": "sample-1.mp3",
        "status": "in_progress",
        "type": "async"
    }
}

###

http://localhost:3000/api/job

###
POST http://localhost:3000/api/job

###
GET http://localhost:3000/api/caption/XNuJmcMoTzCT